#!/usr/bin/env python3

import requests
import time
import urllib.request

t = time.localtime()
current_time = time.strftime("%H:%M:%S", t)
starttime = time.time()

url = input("Please Enter Url: ")
print("Press Ctrl & C to quit")
r = requests.get(url)
count = 0
while r.status_code == 200:
    requests.get(url)
    time.sleep(3.33)
    urllib.request.urlopen(url)
    count += 1
    print("Hit Count: " + str(count))
    time.sleep(3.33)
    print("Current Status Code: " + str(r.status_code))
    time.sleep(3.33)
    r.close()
else:
    print("Url Currently Unavailable")
